### ISSUE TITLE
AssertionError when running using sliding window

### ISSUE THREAD

**Issue by C-MMM** [HuMingLab/SnapHiC#7]
Dear SnapHiC team,
When I run the SnapHiC with the sample dataset using sliding window with binsize=10000.0, I come up an error:

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/bin/anaconda3/envs/SNAPHIC/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/bin/anaconda3/envs/SNAPHIC/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/media/cm/data_DWH/software/SnapHiC/src/rwr.py", line 550, in get_rwr_for_all
    assert rwr_window_size % binsize == 0, "binsize should be a dividend of 10e6"
AssertionError: binsize should be a dividend of 10e6
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/cm/data_DWH/software/SnapHiC/snap.py", line 385, in <module>
    main()
  File "/media/cm/data_DWH/software/SnapHiC/snap.py", line 109, in main
    pool.starmap(get_rwr_for_all, params)
  File "/usr/bin/anaconda3/envs/SNAPHIC/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/bin/anaconda3/envs/SNAPHIC/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AssertionError: binsize should be a dividend of 10e6

How can I solve this problem? Thank you.

**Comment by armenabnousi** [comment]
There was a bug when using threaded mode in rwr window_size computation (after checking your run_script we verified you are using threaded mode). This bug is fixed now. Please use the latest v0.2.3 release as it includes the fix.
